[package]
name = "cxx-qt-example"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.118"
cxx-qt = "0.6.0"
cxx-qt-lib = "0.6.0"

[build-dependencies]
cxx-qt-build = { version = "0.6.0", features = ["link_qt_object_files"] }
